---
- name: My First Playbook
  hosts: tags_Name_IAntonio_Daniels_Ansible
  become: true
  gather_facts: true
  vars_files:
    - "vars.yaml"

  roles:
    #- first_role
    #- second_role
    - bucket_create
    - node_create
    - send_logs

    
  